name: Continue integration server
on:
  pull_request:
    types: [opened, synchronize]
    paths:
      - "server/**"
      - "shared/**"
  push:
    branches: [main]
    paths:
      - "server/**"
      - "shared/**"

jobs:
  build-and-test:
    runs-on: ubuntu-24.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Setup node
        uses: actions/setup-node@v7
        with:
          node-version: 24

      - name: Install dependencies
        run: npm install
        working-directory: ./server
